id: A4C2D7C7A
title: 'Source of Magnificent Blessing: A Prayer to the Lineage of the Secret Practice
  of the Great Compassionate One, Natural Liberation of Suffering'
type: translation
pechas:
- IC46C9C17
- I9C2D816C
- I0D214391
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:33:33.360719
  last_modified_at: 2023-01-04 12:33:33.360747
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IC46C9C17/F9BB: BB11
  I9C2D816C/7597: BB11
  I0D214391/2966: BB11
